version: 0.0
Resources:
 - TargetService:
     Type: AWS::ECS::Service
     Properties:
       TaskDefinition: "arn:aws:ecs:ap-south-1:711610755347:task-definition/bluegreen-task:1"
       LoadBalancerInfo:
         ContainerName: "blue-green-container"
         ContainerPort: 8080
